#!/system/bin/sh

MODDIR=${0%/*}
WIFICFG="WCNSS_qcom_cfg.ini"

# Apply WCNSS cfg overlay generated by customize.sh (AndroPlus-like flow).
if [ -e "${MODDIR}/xml/${WIFICFG}" ]; then
	if [ -e "/odm/vendor/etc/wifi/${WIFICFG}" ]; then
		mount -o ro,bind "${MODDIR}/xml/${WIFICFG}" "/odm/vendor/etc/wifi/${WIFICFG}" >/dev/null 2>&1
	elif [ -e "/vendor/etc/wifi/${WIFICFG}" ]; then
		mount -o ro,bind "${MODDIR}/xml/${WIFICFG}" "/vendor/etc/wifi/${WIFICFG}" >/dev/null 2>&1
	fi
fi

# Apply critical Wi-Fi feature props as early as possible.
BOOT_CC="US"

# Keep boot country locked as US (AndroPlus-style behavior).
resetprop -n ro.boot.wificountrycode "$BOOT_CC"

if command -v iw >/dev/null 2>&1; then
	iw reg set "$BOOT_CC" >/dev/null 2>&1
fi

if command -v cmd >/dev/null 2>&1; then
	cmd wifi force-country-code enabled "$BOOT_CC" >/dev/null 2>&1
	cmd wifi force-country-code "$BOOT_CC" >/dev/null 2>&1
fi

resetprop persist.sys.wifi.country_code "$BOOT_CC"
resetprop persist.vendor.wifi.country_code "$BOOT_CC"
resetprop persist.sys.wifi.default_country_code "$BOOT_CC"
resetprop persist.vendor.wifi.default_country_code "$BOOT_CC"
resetprop persist.vendor.wifi.dynamic_regdom 1
resetprop persist.sys.wifi.dynamic_regdom 1

resetprop persist.vendor.wifi.softap_6ghz_supported 1
resetprop persist.vendor.wifi.softap_6ghz_enabled 1
resetprop persist.vendor.wifi.softap.bridge_mode_supported 1
resetprop persist.vendor.wifi.wifi7_enabled 1
resetprop persist.vendor.wifi.eht_enabled 1
resetprop persist.vendor.wifi.mlo_supported 1
resetprop persist.vendor.wifi.mlo_enabled 1
resetprop persist.vendor.wifi.mlo_softap_supported 1
resetprop persist.vendor.wifi.mlo_sta_supported 1
resetprop persist.vendor.wifi.mlo_link_stats_enabled 1
resetprop persist.vendor.wifi.mlo_link_debug_visible 1
resetprop persist.sys.wifi.softap_6ghz_supported 1
resetprop persist.sys.wifi.mlo_supported 1
resetprop persist.sys.wifi.mlo_enabled 1
resetprop persist.sys.wifi.mlo_link_stats_enabled 1
resetprop persist.sys.wifi.mlo_display_fix 1
resetprop persist.sys.wifi.wifi7_profile 1
resetprop persist.sys.oplus.wifi6ghz.support 1
resetprop persist.sys.oplus.softap6ghz.support 1
resetprop persist.sys.oplus.wifi.mlo.support 1
resetprop persist.sys.oplus.wifi.mlo.display_fix 1
resetprop persist.vendor.oplus.wifi6ghz.support 1
resetprop persist.vendor.oplus.softap6ghz.support 1
resetprop persist.vendor.oplus.wifi.mlo.support 1
resetprop persist.vendor.oplus.wifi.mlo.display_fix 1
resetprop persist.vendor.wifi.dual_ap_supported 1
resetprop persist.vendor.wifi.bridged_ap_supported 1
resetprop persist.vendor.wifi.acs_supported 1
resetprop persist.vendor.wifi.dbs_supported 1
resetprop persist.vendor.wifi.multi_band_scan_supported 1
resetprop persist.vendor.wifi.txpower.dynamic_mode 1
resetprop persist.vendor.wifi.txpower.target_ratio 100
resetprop persist.vendor.wifi.txpower.balance_profile au_1000mw_safety
resetprop persist.vendor.wifi.thermal_throttle_start_c 48
resetprop persist.vendor.wifi.screen_on_perf_priority 1
resetprop persist.vendor.wifi.screen_off_powersave 1
resetprop persist.vendor.wifi.mlo_rebalance_request 0
resetprop persist.sys.wifi.mlo_rebalance_request 0
resetprop persist.sys.opb.wifi.hard_unlock_mode 1
resetprop persist.sys.opb.wifi.hard_unlock_country US
resetprop persist.sys.opb.txpower.max_mbm 3000
resetprop persist.sys.opb.txpower.target_ratio 100
resetprop persist.sys.opb.jp_channel_compat 1
resetprop persist.sys.opb.hotspot_6ghz_force 1
resetprop persist.sys.opb.rf_safety_mode 1
resetprop persist.vendor.wifi.allow_channel_14 1
resetprop persist.vendor.wifi.allow_channel_144 1
resetprop persist.sys.wifi.allow_channel_14 1
resetprop persist.sys.wifi.allow_channel_144 1
resetprop persist.vendor.wifi.jp_channels_compat 1
resetprop persist.vendor.wifi.rx_gain_safety_mode 1
resetprop persist.sys.opb.wifi8.mode 1
resetprop persist.sys.opb.wifi8.coordinated_twt 1
resetprop persist.sys.opb.wifi8.multi_ap_coordination 1
resetprop persist.sys.opb.wifi8.ofdma_multi_ru 1
resetprop persist.sys.opb.wifi8.dso_npca 1
resetprop persist.sys.opb.wifi8.dru_scheduler 1
resetprop persist.vendor.wifi.twt_coordinated_enabled 1
resetprop persist.vendor.wifi.multi_ap_coordination_enabled 1
resetprop persist.vendor.wifi.ofdma_multi_ru_enabled 1
resetprop persist.vendor.wifi.dso_enabled 1
resetprop persist.vendor.wifi.npca_enabled 1
resetprop persist.vendor.wifi.dru_scheduler_enabled 1
resetprop persist.vendor.wifi.ul_dl_mu_mimo_optimized 1
resetprop persist.vendor.wifi.mlo_link_aggregation_enabled 1
resetprop persist.vendor.wifi.roaming_scan_aggressive 1
resetprop persist.vendor.wifi.latency_critical_path 1
resetprop persist.sys.opb.wifi.force_mode 0
resetprop persist.sys.opb.wifi.force_country_code ""
resetprop persist.vendor.opb.wifi.force_country_code ""
